// src/app/(auth)/login/page.jsx
import React from 'react';
import Link from 'next/link';

import { genPageMetadata } from '@/app/seo';
import { GitHubIcon } from '@/components/Common/CustomIcons';

export const metadata = genPageMetadata({
  title: 'Masuk — Kelola Project Anda',
  description: 'Masuk ke akun BikinProject untuk mulai mengelola project generator Anda.',
});

const Login = () => {
  return (
    <section className="min-h-[80vh] flex items-center justify-center p-4">
      <div className="w-full max-w-md bg-white dark:bg-zinc-950 rounded-3xl border-2 border-zinc-100 dark:border-zinc-800 shadow-2xl overflow-hidden">
        <div className="bg-zinc-50 dark:bg-zinc-900/50 px-6 py-4 border-b-2 border-zinc-100 dark:border-zinc-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xl">📦</span>
            <span className="font-mono font-bold text-zinc-900 dark:text-white">auth --login</span>
          </div>
          <div className="flex gap-1.5 opacity-30">
            <div className="w-3 h-3 rounded-full bg-zinc-400" />
            <div className="w-3 h-3 rounded-full bg-zinc-400" />
            <div className="w-3 h-3 rounded-full bg-zinc-400" />
          </div>
        </div>

        <div className="p-8 space-y-8">
          <div className="text-center space-y-2">
            <h1 className="text-3xl font-black text-zinc-950 dark:text-white">Selamat Datang</h1>
            <p className="text-zinc-500 dark:text-zinc-400 font-medium">
              Masuk untuk mengelola project Anda.
            </p>
          </div>

          <form className="space-y-5">
            <div className="space-y-2">
              <label
                htmlFor="email"
                className="block text-sm font-bold text-zinc-700 dark:text-zinc-300 font-mono"
              >
                $ user.email
              </label>
              <input
                type="email"
                id="email"
                className="w-full bg-zinc-50 dark:bg-zinc-900 border-2 border-zinc-100 dark:border-zinc-800 rounded-2xl px-5 py-3.5 focus:outline-none focus:border-blue-600 dark:focus:border-blue-500 transition-all font-mono text-zinc-900 dark:text-white placeholder:text-zinc-400"
                placeholder="email@example.com"
                required
              />
            </div>

            <div className="space-y-2">
              <label
                htmlFor="password"
                className="block text-sm font-bold text-zinc-700 dark:text-zinc-300 font-mono"
              >
                $ user.password
              </label>
              <input
                type="password"
                id="password"
                className="w-full bg-zinc-50 dark:bg-zinc-900 border-2 border-zinc-100 dark:border-zinc-800 rounded-2xl px-5 py-3.5 focus:outline-none focus:border-blue-600 dark:focus:border-blue-500 transition-all font-mono text-zinc-900 dark:text-white placeholder:text-zinc-400"
                placeholder="••••••••"
                required
              />
            </div>

            <button
              type="submit"
              className="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white font-black rounded-2xl shadow-xl shadow-blue-500/20 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] mt-4"
            >
              Masuk Ke Sistem
            </button>

            <div className="relative flex items-center justify-center">
              <span className="absolute inset-x-0 h-px bg-zinc-100 dark:bg-zinc-800"></span>
              <span className="relative bg-white dark:bg-zinc-950 px-4 text-xs font-bold text-zinc-400 uppercase tracking-widest">
                Atau
              </span>
            </div>

            <button className="w-full flex items-center justify-center gap-3 py-3.5 rounded-2xl border-2 border-zinc-100 dark:border-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-900 transition-all font-bold text-zinc-900 dark:text-white">
              <GitHubIcon />
              <span>GitHub Authentication</span>
            </button>
          </form>

          <p className="text-center text-zinc-500 dark:text-zinc-400 font-medium">
            Belum punya akun?{' '}
            <Link
              href="/auth/register"
              className="text-blue-600 dark:text-blue-400 font-bold hover:underline"
            >
              Daftar Sekarang
            </Link>
          </p>
        </div>
      </div>
    </section>
  );
};

export default Login;

// src/app/(auth)/login.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { GitHubIcon } from '@/components/Common/CustomIcons'
import MainLayout from '@/layouts/MainLayout.vue'
import { useSeo } from '@/hooks/useSeo'

useSeo({
  title: 'Login',
  description: 'Masuk ke akun BikinProject Anda.',
})
</script>

<template>
  <MainLayout>
    <section
      class="min-h-screen flex items-center justify-center p-4 bg-white dark:bg-zinc-950 transition-colors duration-300"
    >
      <div
        class="w-full max-w-md bg-white dark:bg-zinc-950 rounded-3xl border-2 border-zinc-100 dark:border-zinc-800 shadow-2xl overflow-hidden"
      >
        <div
          class="bg-zinc-50 dark:bg-zinc-900/50 px-6 py-4 border-b-2 border-zinc-100 dark:border-zinc-800 flex items-center justify-between"
        >
          <div class="flex items-center gap-2">
            <span class="text-xl">📦</span>
            <span class="font-mono font-bold text-zinc-900 dark:text-white">auth --login</span>
          </div>
          <div class="flex gap-1.5 opacity-30">
            <div class="w-3 h-3 rounded-full bg-zinc-400" />
            <div class="w-3 h-3 rounded-full bg-zinc-400" />
            <div class="w-3 h-3 rounded-full bg-zinc-400" />
          </div>
        </div>

        <div class="p-8 space-y-8">
          <div class="text-center space-y-2">
            <h1 class="text-3xl font-black text-zinc-950 dark:text-white">Selamat Datang</h1>
            <p class="text-zinc-500 dark:text-zinc-400 font-medium">
              Masuk untuk mengelola project Anda.
            </p>
          </div>

          <form class="space-y-5">
            <div class="space-y-2">
              <label
                for="email"
                class="block text-sm font-bold text-zinc-700 dark:text-zinc-300 font-mono"
              >
                $ user.email
              </label>
              <input
                type="email"
                id="email"
                class="w-full bg-zinc-50 dark:bg-zinc-900 border-2 border-zinc-100 dark:border-zinc-800 rounded-2xl px-5 py-3.5 focus:outline-none focus:border-blue-600 dark:focus:border-blue-500 transition-all font-mono text-zinc-900 dark:text-white placeholder:text-zinc-400 dark:placeholder:text-zinc-500"
                placeholder="email@example.com"
                required
              />
            </div>

            <div class="space-y-2">
              <label
                for="password"
                class="block text-sm font-bold text-zinc-700 dark:text-zinc-300 font-mono"
              >
                $ user.password
              </label>
              <input
                type="password"
                id="password"
                class="w-full bg-zinc-50 dark:bg-zinc-900 border-2 border-zinc-100 dark:border-zinc-800 rounded-2xl px-5 py-3.5 focus:outline-none focus:border-blue-600 dark:focus:border-blue-500 transition-all font-mono text-zinc-900 dark:text-white placeholder:text-zinc-400 dark:placeholder:text-zinc-500"
                placeholder="••••••••"
                required
              />
            </div>

            <button
              type="submit"
              class="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white font-black rounded-2xl shadow-xl shadow-blue-500/20 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] mt-4"
            >
              Masuk Ke Sistem
            </button>

            <div class="relative flex items-center justify-center">
              <span class="absolute inset-x-0 h-px bg-zinc-100 dark:bg-zinc-800"></span>
              <span
                class="relative bg-white dark:bg-zinc-950 px-4 text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-widest"
              >
                Atau
              </span>
            </div>

            <button
              class="w-full flex items-center justify-center gap-3 py-3.5 rounded-2xl border-2 border-zinc-100 dark:border-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-900 transition-all font-bold text-zinc-900 dark:text-white"
            >
              <GitHubIcon />
              <span>GitHub Authentication</span>
            </button>
          </form>

          <p class="text-center text-zinc-500 dark:text-zinc-400 font-medium">
            Belum punya akun?
            <RouterLink
              to="/register"
              class="text-blue-600 dark:text-blue-400 font-bold hover:underline"
            >
              Daftar Sekarang
            </RouterLink>
          </p>
        </div>
      </div>
    </section>
  </MainLayout>
</template>
