// src/routes/(root)/contact/index.jsx
import { createFileRoute } from '@tanstack/react-router'

import { siteMetadata } from '@/data/siteMetadata'

const Contact = () => {
  return (
    <section className="flex items-center justify-center min-h-screen bg-white dark:bg-zinc-950 text-zinc-950 dark:text-white transition-colors duration-300">
      <div className="container">
        <div className="flex flex-wrap">
          <div className="w-full px-4">
            <section className="body-font">
              <div className="container mx-auto flex items-center justify-center flex-col">
                <div className="relative group lg:w-2/6 md:w-3/6 w-5/6 mb-10 overflow-hidden rounded-3xl shadow-2xl border-2 border-zinc-100 dark:border-zinc-800 transition-all duration-300">
                  <img
                    src="https://avatars.githubusercontent.com/u/83068205?v=4"
                    loading="lazy"
                    alt="hero"
                    className="w-full h-full object-cover object-center transition-transform duration-500 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-zinc-950/20 to-transparent" />
                </div>

                <div className="text-center lg:w-2/3 w-full space-y-4">
                  <h1 className="text-4xl md:text-5xl font-extrabold text-zinc-950 dark:text-white leading-tight">
                    Naufal Akbar Nugroho
                  </h1>

                  <h2 className="text-xl md:text-2xl font-semibold text-blue-600 dark:text-blue-400">
                    Fullstack Web Developer | Undergraduate Information Systems Student
                  </h2>

                  <p className="max-w-xl mx-auto text-lg md:text-xl text-zinc-700 dark:text-zinc-400 leading-relaxed font-medium">
                    Saya bersemangat memberikan kontribusi untuk memberikan pengetahuan teknologi
                    bagi semua orang!
                  </p>

                  <div className="flex justify-center gap-4 pt-6">
                    <a
                      href={siteMetadata.github}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex text-white bg-blue-600 hover:bg-blue-700 border-0 py-3 px-8 focus:outline-none rounded-2xl text-lg font-bold shadow-xl shadow-blue-500/20 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
                    >
                      GitHub Saya
                    </a>

                    <a
                      href={`mailto:${siteMetadata.email}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex text-zinc-900 dark:text-white bg-zinc-100 dark:bg-zinc-900 border-2 border-zinc-200 dark:border-zinc-800 py-3 px-8 focus:outline-none hover:bg-zinc-200 dark:hover:bg-zinc-800 rounded-2xl text-lg font-bold transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
                    >
                      Hubungi Saya
                    </a>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </section>
  )
}

export const Route = createFileRoute('/(root)/contact/')({
  head: () => ({
    meta: [
      {
        title: `Kontak | ${siteMetadata.title}`,
      },
      {
        name: 'description',
        content: `Hubungi kami untuk kolaborasi atau pertanyaan terkait ${siteMetadata.title}.`,
      },
    ],
  }),
  component: Contact,
})

// src/app/(root)/contact.vue
<script setup lang="ts">
import { siteMetadata } from '@/data/siteMetadata'
import MainLayout from '@/layouts/MainLayout.vue'
import { useSeo } from '@/hooks/useSeo'

useSeo({
  title: 'Kontak',
  description: 'Hubungi tim BikinProject untuk informasi lebih lanjut.',
})
</script>

<template>
  <MainLayout>
    <section
      class="flex items-center justify-center min-h-screen bg-white dark:bg-zinc-950 text-zinc-950 dark:text-white transition-colors duration-300"
    >
      <div class="container">
        <div class="flex flex-wrap">
          <div class="w-full px-4">
            <section class="body-font">
              <div class="container mx-auto flex items-center justify-center flex-col">
                <div
                  class="relative group lg:w-2/6 md:w-3/6 w-5/6 mb-10 overflow-hidden rounded-3xl shadow-2xl border-2 border-zinc-100 dark:border-zinc-800 transition-all duration-300"
                >
                  <img
                    src="https://avatars.githubusercontent.com/u/83068205?v=4"
                    loading="lazy"
                    alt="hero"
                    class="w-full h-full object-cover object-center transition-transform duration-500 group-hover:scale-110"
                  />
                  <div class="absolute inset-0 bg-gradient-to-t from-zinc-950/20 to-transparent" />
                </div>

                <div class="text-center lg:w-2/3 w-full space-y-4">
                  <h1
                    class="text-4xl md:text-5xl font-extrabold text-zinc-950 dark:text-white leading-tight"
                  >
                    Naufal Akbar Nugroho
                  </h1>

                  <h2 class="text-xl md:text-2xl font-semibold text-blue-600 dark:text-blue-400">
                    Fullstack Web Developer | Undergraduate Information Systems Student
                  </h2>

                  <p
                    class="max-w-xl mx-auto text-lg md:text-xl text-zinc-700 dark:text-zinc-400 leading-relaxed font-medium"
                  >
                    Saya bersemangat memberikan kontribusi untuk memberikan pengetahuan teknologi
                    bagi semua orang!
                  </p>

                  <div class="flex justify-center gap-4 pt-6">
                    <a
                      :href="siteMetadata.github"
                      target="_blank"
                      rel="noopener noreferrer"
                      class="inline-flex text-white bg-blue-600 hover:bg-blue-700 border-0 py-3 px-8 focus:outline-none rounded-2xl text-lg font-bold shadow-xl shadow-blue-500/20 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
                    >
                      GitHub Saya
                    </a>

                    <a
                      :href="`mailto:${siteMetadata.email}`"
                      target="_blank"
                      rel="noopener noreferrer"
                      class="inline-flex text-zinc-900 dark:text-white bg-zinc-100 dark:bg-zinc-900 border-2 border-zinc-200 dark:border-zinc-800 py-3 px-8 focus:outline-none hover:bg-zinc-200 dark:hover:bg-zinc-800 rounded-2xl text-lg font-bold transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
                    >
                      Hubungi Saya
                    </a>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </section>
  </MainLayout>
</template>
