// src/layouts/MainLayout.vue
<script setup lang="ts">
import Navbar from '@/components/Mixins/Navbar/index.vue'
import Footer from '@/components/Mixins/Footer.vue'
import ScrollToTop from '@/components/Common/ScrollToTop.vue'
import { useSeo } from '@/composables/useSeo'

useSeo()
</script>

<template>
  <Navbar />
  <main class="min-h-screen">
    <slot />
  </main>
  <ScrollToTop />
  <Footer />
</template>

// src/layouts/MainLayout.tsx
import { FC, ReactNode } from 'react';

import Navbar from '@/components/Mixins/Navbar';
import Footer from '@/components/Mixins/Footer';

type Props = {
  children: ReactNode;
};

const MainLayout: FC<Props> = ({ children }) => {
  return (
    <>
      <Navbar />

      <main>{children}</main>

      <Footer />
    </>
  );
};

export default MainLayout;
