// src/layouts/MainLayout.vue
<script setup lang="ts">
import Navbar from '@/components/Mixins/Navbar/index.vue'
import Footer from '@/components/Mixins/Footer.vue'
import ScrollToTop from '@/components/Common/ScrollToTop.vue'
import { useSeo } from '@/composables/useSeo'

useSeo()
</script>

<template>
  <Navbar />
  <main class="min-h-screen">
    <slot />
  </main>
  <ScrollToTop />
  <Footer />
</template>

// src/layouts/MainLayout.jsx
import React from 'react';

import Navbar from '@/components/Mixins/Navbar/Navbar';
import Footer from '@/components/Mixins/Footer';

const MainLayout = ({ children }) => {
  return (
    <>
      <Navbar />

      <main className="pt-24 pb-24 mt-40 mb-40">{children}</main>

      <Footer />
    </>
  );
};

export default MainLayout;
